@echo off
echo 🔒 Running Security Scans...

echo 1. SAST with Trivy...
trivy fs .

echo 2. Container vulnerability scanning...
trivy image ranaromdhane/book-recommendation-api:latest

echo 3. Dependency vulnerability scan...
npm audit --audit-level moderate

echo 4. Secret detection...
echo Note: git-secrets not available on Windows, skipping...

echo ✅ Security scans completed
pause