apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-recommendation-api
  labels:
    app: book-api
spec:
  replicas: 1  # Use 1 replica for faster startup
  selector:
    matchLabels:
      app: book-api
  template:
    metadata:
      labels:
        app: book-api
    spec:
      containers:
      - name: book-api
        image: book-recommendation-api:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        # Remove all probes for CI/CD to avoid timeouts
        # Remove resource limits for faster scheduling
        command: ["node"]
        args: ["src/server.js"]