apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-recommendation-api
  labels:
    app: book-api
spec:
  replicas: 1  # Reduce to 1 for faster startup
  selector:
    matchLabels:
      app: book-api
  template:
    metadata:
      labels:
        app: book-api
    spec:
      containers:
      - name: book-api
        image: book-recommendation-api:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        # Remove resource limits for CI/CD
        # Remove probes for CI/CD to avoid timeouts
        command: ["node"]
        args: ["src/server.js"]
        # Add startup probe instead of readiness/liveness
        startupProbe:
          httpGet:
            path: /health
            port: 3000
          failureThreshold: 30  # Allow many failures
          periodSeconds: 5