apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-recommendation-api
  labels:
    app: book-api
spec:
  replicas: 1  # Use only 1 replica in CI/CD for faster startup
  selector:
    matchLabels:
      app: book-api
  template:
    metadata:
      labels:
        app: book-api
    spec:
      containers:
      - name: book-api
        image: book-recommendation-api:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        # Remove resource limits for faster scheduling
        # Use startup probe instead of readiness/liveness
        startupProbe:
          httpGet:
            path: /health
            port: 3000
          failureThreshold: 30  # Allow many failures
          periodSeconds: 10     # Check every 10 seconds
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10